### ISSUE TITLE
Loom links on right reset when clicked

### ISSUE THREAD

**Issue by GarretteBaker** [cosmicoptima/loom#1]
While scanning through the possible completions, and there are enough possible completions to fill the page and then some like so

![image](https://user-images.githubusercontent.com/96269146/221502144-8eec33c6-bbd5-4279-8e19-bb97b400afb9.png)

If I click on a possible completion (like ". His jaw dropped[...]"), then I get reset back to the top of the completions panel, and my view then looks like this

![image](https://user-images.githubusercontent.com/96269146/221502300-81b46197-f79e-4380-8b94-d1aa75f7a983.png)

**Comment by cosmicoptima** [comment]
fixed, or i think i did
