### ISSUE TITLE
Graph view gone?

### ISSUE THREAD

**Issue by dfischer** [cosmicoptima/loom#10]
I just updated loom and I can't seem to find the graph view anymore and the shortcut hotkey disappeared as well?

**Comment by cosmicoptima** [comment]
sorry, it was complicating the codebase and i didn't think many people were using it. i'll re-add it at some point

**Comment by cosmicoptima** [comment]
i'll close the issue once i've done so. i might not re-add infills, let me know if you used/liked them

**Comment by dfischer** [comment]
Thank you. I didn't understand infills actually. I liked the branching visual nature to compare things. It was nice for at least... getting a "feel" for what is going on.

**Comment by dfischer** [comment]
How do you visualize keep track of all the things in your workflow without it?
