### ISSUE TITLE
[Feature] Open-source PKM port?

### ISSUE THREAD

**Issue by nicholaskross** [cosmicoptima/loom#12]
Might be out of scope for this repo, but I'd be pretty psyched for it to happen. Basically, the same functionality but for something like [SiYuan](https://github.com/siyuan-note/siyuan).

**Comment by cosmicoptima** [comment]
siyuan looks good; if someone ports loomsidian to it, i may be willing to maintain it, but i'm not sure i want to do that myself

**Comment by cosmicoptima** [comment]
wait, siyuan uses notion-style blocks:

![image](https://github.com/cosmicoptima/loom/assets/80304394/b6856b0b-d365-402f-9849-b55bcfac9e3a)

which would complicate porting loom to it significantly. can you think of an elegant way to do that? otherwise i would recommend different software

**Comment by cosmicoptima** [comment]
i think this is out of scope for me sorry
