### ISSUE TITLE
Main text window resets after generations

### ISSUE THREAD

**Issue by GarretteBaker** [cosmicoptima/loom#2]
Occasionally the main text window will reset when I've generated a bunch of text. I think the cause is me being scrolled all the way down.

**Comment by cosmicoptima** [comment]
to be sure, you mean the editor in the center of the window, which contains the full text corresponding to the selected node?

> I think the cause is me being scrolled all the way down.

like, scrolled all the way down in the editor, or in the tree ui?

when exactly does this happen? eg does it happen upon scrolling to a certain point, or upon switching nodes, or upon running a certain command or using a certain shortcut?

(sorry for slow reply; i took a break from loomsidian work and should be more active now)

**Comment by GarretteBaker** [comment]
It happens when scrolling all the way down, and switching nodes. Any node, as far as I can tell.

-Garrett Baker

**Comment by cosmicoptima** [comment]
how is it now? i think i fixed this

**Comment by GarretteBaker** [comment]
Yup, looks like its fixed
