### ISSUE TITLE
openrouter llama 405-base not returning multiple completions

### ISSUE THREAD

**Issue by GarretteBaker** [cosmicoptima/loom#21]
some information:
![image](https://github.com/user-attachments/assets/0f9aedda-6e5b-4506-a884-6cbf793243ee)
![image](https://github.com/user-attachments/assets/ce2a9d33-2703-4aaa-9e4c-d638e5c23b89)
![image](https://github.com/user-attachments/assets/9cfe866e-7c62-4771-a0d7-e0cdca0f28c5)

api key of course left out

**Comment by cosmicoptima** [comment]
yes, that's because openrouter ignores the n parameter. loomsidian will need to manually implement n for openrouter by making simultaneous requests

**Comment by cosmicoptima** [comment]
OpenRouter is now listed as a separate provider. Using that will fix this problem
