### ISSUE TITLE
[Feature request] Jump to node when I click on a passage

### ISSUE THREAD

**Issue by GarretteBaker** [cosmicoptima/loom#3]
I often find myself wanting to backtrack, and I always get lost when doing so. I feels like I should be able to click on a section in the text, and have that take me to the relevant node. Can this be implemented?

**Comment by cosmicoptima** [comment]
yeah, i can implement that. i will try to today

**Comment by cosmicoptima** [comment]
i'm going to implement it as shift+click. let me know if you'd rather it be on click
