### ISSUE TITLE
[Bug] Old/generated text differentiation breaks

### ISSUE THREAD

**Issue by GarretteBaker** [cosmicoptima/loom#4]
I'm unable to figure out what causes the problem, but occasionally after generating a bunch, the shading for old text will become the same as the shading for the new text. Most of the time it gets fixed by going into a different file, but not always. I'm not certain what the triggering event is.

**Comment by GarretteBaker** [comment]
A possible hint about what's happening: it seems that when this happens, the 'generate from current position' functionality reverts to the 'generate from the end-position' functionality

**Comment by cosmicoptima** [comment]
i've fixed this in some cases, but i think it still happens sometimes. it's rare enough that i haven't been able to reproduce it, but i'm going to keep this open since there _is_ still a bug that manifests like this

**Comment by cosmicoptima** [comment]
this happens when the `update` method in my editor plugin errors due to not accounting for the structure of the document that's passed in. i'm confused right now about how the editor's content maps to said structure

**Comment by cosmicoptima** [comment]
@GarretteBaker -- have you had this problem since?

**Comment by CrazyPython** [comment]
yes it still happens
