### ISSUE TITLE
Loom 1.9.1 wiped out node/branch data

### ISSUE THREAD

**Issue by Quandrant** [cosmicoptima/loom#8]
Hello, I am running Loomsidian 1.9.1 on Obsidian v1.2.8 on macOS Ventura 13.0.1 on M1 iMac alongside community plugin "Find orphaned files and broken links" with a stable internet connection.

*What steps will reproduce the problem?*

1. Open a WIP note with many nodes and deep, linear subbranches.
2. Work on the file -- typing, editing, generating, etc.
3. Entire Obsidian application window goes white/gray.
4. Reopen the Obsidian program.
5. Survey the notes and Loomsidian sidebar.

*What is the expected result?*

All of the branches of the sidebar should be available.

*What happens instead?*

It wipes out the node and (sub)branch data, only leaving the latest known version of the note available as a single node.

*Please provide additional information if possible.*

I checked out the data.json and the size of the file fell from 600+ kilobytes to 140 kilobytes. This implies to me that the plugin did not lose just access to the data in .json; it actually overwrote the data.

I also suspect this problem is related to the new performance problems of the 1.9.X releases (I had no problem editing deep branches in 1.8.0), so the application window going blank may denote some crash on the background.

I still have a backup of my plugin from 3 days ago, so I haven't lost too much, but backups should be **strongly** encouraged.

**Comment by cosmicoptima** [comment]
i will ask if anyone else has lost data

**Comment by Quandrant** [comment]
Almost(!!) forgot about this. Loom 1.10 and higher definitely much more stable, and haven't lost any data since. Thanks for your hard work!

**Comment by cosmicoptima** [comment]
yw!
